In [4]:
import numpy as np

#### 1.길이가 10인 0-벡터를 만드세요.

In [23]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 2. 길이가 10이며 다섯번째 원소만 1이고 나머지 원소는 모두 0인 벡터를 만드세요.

In [25]:
np.where(np.arange(10)==4, 1, 0)

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [47]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.eye(N=1, M=10, k=4).flatten(10, )

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Non-string object detected for the array ordering. Please pass in 'C', 'F', 'A', or 'K' instead
  """Entry point for launching an IPython kernel.


array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 3. 10 부터 49까지의 값을 가지는 벡터를 만드세요.

In [9]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 4. 위(3번) 벡터의 순서를 바꾸세요.

In [22]:
np.arange(49, 9, -1)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 5. 0부터 8까지의 값을 가지는 3x3 행렬을 만드세요.

In [12]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 6. 벡터 [1,2,0,0,4,0] 에서 원소의 값이 0이 아닌 원소만 선택한 벡터를 만드세요.

In [31]:
a = np.array([1,2,0,0,4,0])
a[a!=0]


array([1, 2, 4])

In [32]:
a!=0

array([ True,  True, False, False,  True, False])

#### 7. 3x3 단위 행렬(identity matrix)을 만드세요


In [18]:
np.identity(n=3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 8. 난수 원소를 가지는 3x3 행렬을 만드세요

In [35]:
random = np.random.random(9).reshape(3,3)
print(random)

[[0.81622475 0.27407375 0.43170418]
 [0.94002982 0.81764938 0.33611195]
 [0.17541045 0.37283205 0.00568851]]


#### 9. 위(8번)에서 만든 난수 행렬에서 최대값/최소값 원소를 찾으세요.

In [46]:
np.max(random), np.min(random)

(0.9400298196223746, 0.005688507352573424)

#### 10. 위(8번)에서 만든 난수 행렬에서 행 평균, 열 평균을 계산하세요.

In [37]:
np.mean(random, axis=1)

array([0.50733423, 0.69793038, 0.18464367])

In [38]:
np.mean(random, axis=0)

array([0.64388834, 0.48818506, 0.25783488])